server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
              - "https://pgt-frontend.pages.dev"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: ms-administration-auth
          uri: lb://ms-administration
          predicates:
            - Path=/api/v1/auth/**
        
        - id: ms-administration-users
          uri: lb://ms-administration
          predicates:
            - Path=/api/v1/users/**
        
        - id: ms-administration-accounts
          uri: lb://ms-administration
          predicates:
            - Path=/api/v1/accounts/**

        - id: ms-administration-roles
          uri: lb://ms-administration
          predicates:
            - Path=/api/v1/roles/**
        
        - id: ms-inventory-locations
          uri: lb://ms-inventory
          predicates:
            - Path=/api/v1/locations/**

        - id: ms-inventory-warehouses
          uri: lb://ms-inventory
          predicates:
            - Path=/api/v1/warehouses/**

        - id: ms-inventory-products
          uri: lb://ms-inventory
          predicates:
            - Path=/api/v1/products/**

        - id: ms-inventory-categories
          uri: lb://ms-inventory
          predicates:
            - Path=/api/v1/categories/**

        - id: ms-inventory-brands
          uri: lb://ms-inventory
          predicates:
            - Path=/api/v1/brands/**

        - id: ms-inventory-movements
          uri: lb://ms-inventory
          predicates:
            - Path=/api/v1/movimientos/**
        - id: ms-inventory-kardex
          uri: lb://ms-inventory
          predicates:
            - Path=/api/v1/kardex/**
        - id: ms-inventory-dashboard
          uri: lb://ms-inventory
          predicates:
            - Path=/api/v1/dashboard/**
        - id: ms-inventory-heatmap
          uri: lb://ms-inventory
          predicates:
            - Path=/api/v1/heatmap/**
        - id: ms-inventory-ws
          uri: lb://ms-inventory
          predicates:
            - Path=/ws/**

        - id: ms-tracking-picking
          uri: lb://ms-tracking
          predicates:
            - Path=/api/v1/picking/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    ip-address: 127.0.0.1